### ISSUE TITLE
HOW

### ISSUE THREAD

**Issue by greasygaijin** [ClonkAndre/ClonksCodingLib.GTAIV#3]
HOW

**Comment by azeman** [comment]
no tutorial whatsoever, his mods stop the game from running, absolute rubbish

**Comment by ClonkAndre** [comment]
Sorry if you are too incompetent to come up with the idea to drop a single .dll file within the main directory of GTA IV where all the other dll files are. Also the mod itself can change the location of where it reads its dll files, so its up to the mod where this file gets placed. Closing as completed!
